#!/bin/bash
#
# Wrapper around make, to colorize it's output and pipe through less.
# Jumps to the first gcc error that occurs during the build process.
#
# Run with --short as the first argument to shorten each line so it fits
# on the screen.
#

if [ "$TERM" = "dumb" ];then
   # As suggested by Alexander Korkov ...
   exec "$@"
fi


# Pipe through less only if we are invoked as clmake.
if [ "$(basename $0 |cut -f1 -d-)" = "bake" ]; then
    #echo "1 - $@"
    $@ 2>&1 | beautify
else
    #echo "2 - $@"
    $@ 2>&1 | colormake.pl
fi

# Thanks to Alexander Korkov and Kolan Sh
exit ${PIPESTATUS[0]}
