#!/usr/bin/perl -w

#
#
#----------------------------------
#USAGE # PRPG | colorline
#-----------------------------------
#
#

#Adding Color to Your Output From C
#----------------------------------
#   CODE        COLOR
#----------------------------------
#   [0;31m      Red
#   [1;31m      Bold Red
#   [0;32m      Green
#   [1;32m      Bold Green
#   [0;33m      Yellow
#   [1;33m      Bold Yellow
#   [0;34m      Blue
#   [1;34m      Bold Blue
#   [0;35m      Magenta
#   [1;35m      Bold Magenta
#   [0;36m      Cyan
#   [1;36m      Bold Cyan
#   [0m         Reset

while(<STDIN>) {
    my $line = $_;
    chomp($line);
    for($line){
        s/==>.*<==/\e[1;44m$&\e[0m/gi;                      #tail multiples files name in blue background
        s/.*exception.*|at .*/\e[0;31m$&\e[0m/gi;           #java errors & stacktraces in red
        s/Info/\e[0;32m$&\e[0m/gi;                          #info replacement in green
        s/Warning|Warn/\e[1;33m$&\e[0m/gi;                  #warning replacement in yellow
        s/Cleaning|Clean/\e[1;33m$&\e[0m/gi;                #warning replacement in yellow
        s/Log|Logfile|Logging|Syslog/\e[1;33m$&\e[0m/gi;           #warning replacement in yellow
        s/Package|Packages/\e[1;33m$&\e[0m/gi;              #warning replacement in green bold
        s/Collect/\e[0;35m$&\e[0m/gi;                       #info replacement in magnenta normal
        s/git|rm|grep/\e[0;31m$&\e[0m/gi;                   #info replacement in magnenta normal
        s/Success|Succeeded|Succeed/\e[1;32m$&\e[0m/gi;     #info replacement in green bold
        s/Failed|Fail/\e[1;31m$&\e[0m/gi;                   #info replacement in red bold
        s/Compiling|Compile/\e[1;35m$&\e[0m/gi;             #info replacement in magnenta bold
        s/Note/\e[1;34m$&\e[0m/gi;                          #info replacement in blue bold
        s/Linking|Link/\e[0;35m$&\e[0m/gi;                  #info replacement in magnenta normal
        s/gcc/\e[1;35m$&\e[0m/gi;                           #info replacement in magnenta bold
        s/'g++'/\e[1;35m$&\e[0m/gi;                         #info replacement in magnenta bold
        s/Makefile|Make/\e[0;35m$&\e[0m/gi;                 #info replacement in magnenta normal
        s/Building|Build/\e[0;35m$&\e[0m/gi;                #info replacement in magnenta normal
        s/Error/\e[1;31m$&\e[0m/gi;                         #info replacement in red bold
        s/Summary/\e[1;34m$&\e[0m/gi;                       #info replacement in blue bold
        # s/Succ.*/\e[1;32m$&\e[0m/gi;                        #info replacement in green bold (COLOR entire line after .*)
        # s/\bError\b/\e[1;31m$&\e[0m/gi;                     #info replacement in red bold (word bound - only specific word match)a
        # s/Summary.*/\e[1;34m$&\e[0m/gi;                     #info replacement in blue bold (COLOR entore lime after *)

    }
    print $line, "\n";
}

