#!/usr/bin/perl -w

#
#
#----------------------------------
#USAGE # PRPG | colorline
#-----------------------------------
#
#

#---
#tail | awk '/INFO/ {print "\033[32m" $0 "\033[39m"} /SEVERE/ {print "\033[31m" $0 "\033[39m"}'
#
#./re-get-sourses -clean| | perl -pe 's/.*tm.*/\e[1;31m$&\e[0m/g'
#
#
#tail -f file.log | awk '/Clean/ {print "\033[32m" $0 "\033[39m"} /tmu/ {print "\033[31m" $0 "\033[39m"}'
#-----


#Adding Color to Your Output From C
#----------------------------------
#   CODE        COLOR
#----------------------------------
#   [0;31m      Red
#   [1;31m      Bold Red
#   [0;32m      Green
#   [1;32m      Bold Green
#   [0;33m      Yellow
#   [1;33m      Bold Yellow
#   [0;34m      Blue
#   [1;34m      Bold Blue
#   [0;35m      Magenta
#   [1;35m      Bold Magenta
#   [0;36m      Cyan
#   [1;36m      Bold Cyan
#   [0m         Reset

while(<STDIN>) {
    my $line = $_;
    chomp($line);
    for($line){
        s/==>.*<==/\e[1;44m$&\e[0m/gi; #tail multiples files name in blue background
        s/.*exception.*|at .*/\e[0;31m$&\e[0m/gi;  #java errors & stacktraces in red
        s/info.*/\e[0;32m$&\e[0m/gi; #info replacement in green
        s/warning.*/\e[1;33m$&\e[0m/gi; #warning replacement in yellowa
        s/Clean.*/\e[1;33m$&\e[0m/gi; #warning replacement in yellow
        s/Warning.*/\e[1;33m$&\e[0m/gi; #warning replacement in yellow
        s/Warn.*/\e[1;33m$&\e[0m/gi; #warning replacement in yellow
        s/Success.*/\e[1;32m$&\e[0m/gi; #info replacement in green bold
        s/Succ.*/\e[1;32m$&\e[0m/gi; #info replacement in green bold
        s/Fail.*/\e[1;31m$&\e[0m/gi; #info replacement in red bold
        s/Compile.*/\e[1;35m$&\e[0m/gi; #info replacement in magnenta normal
        s/Note.*/\e[0;32m$&\e[0m/gi; #info replacement in green normal
        s/Linking*/\e[0;35m$&\e[0m/gi; #info replacement in magnenta normal
        s/Build.*/\e[0;35m$&\e[0m/gi; #info replacement in magnenta normal
        s/Error.*/\e[1;31m$&\e[0m/gi; #info replacement in red bold
        s/Summary.*/\e[1;34m$&\e[0m/gi; #info replacement in blue bold
    }
    print $line, "\n";
}

