#!/bin/bash
echo "Looking Up Sourse Files Recurssively"
#find . -name "*.c" -o -name "*.cpp" -o -name "*.cc" -o -name "*.h" -o -name "*.hpp" > cscope.files
find . -name "*.c" -o -name "*.cc" -o -name "*.cpp" -o -name "*.h" -o -name "*.hh" -o -name "*.hpp" -o -name "*.py" > cscope.files

echo "Creating Cscope Database"
cscope -q -R -b -i cscope.files

#Generate ctags also
echo "Creating Ctags Database"
#ctags -R --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++ -V .
ctags --langmap=C++:+.inc --c++-kinds=+p --fields=+iaS --extra=+fq --sort=foldcase -R -L cscope.files

echo "Cleanup File List"
rm -rf cscope.files

ls -lh cscope* tags*
echo "Ctags And Cscope Database Creation Successful"


