#!/bin/bash

function usage {
    echo "Usage : `basename $0` < -g | -s | -c | -e | -f > < string >"
    echo "Usage : `basename $0` < -vg | -vs | -vc | -ve | -vf > < string >"
    echo "Options :"
    echo "        -[v]g    : Global Definaton"
    echo "        -[v]s    : Lookup Symbol"
    echo "        -[v]c    : Search Caller"
    echo "        -[v]e    : Egrep string"
    echo "        -[v]f    : Lookup File Partten"
}

if [ $# -eq 0 ]
then
    usage
    exit
fi

if [ ! -f cscope.out ];then
    echo "Cscope Database Doesn't Exist In The Current Path"
    exit
fi

if [ "$1" == "-g" ] || [ "$1" == "-s" ] || [ "$1" == "-c" ] || [ "$1" == "-e" ] || [ "$1" == "-f" ] ||
    [ "$1" == "-vg" ] || [ "$1" == "-vs" ] || [ "$1" == "-vc" ] || [ "$1" == "-ve" ] || [ "$1" == "-vf" ];then
    if [  -z "$2" ];then
        echo "Must pass search args"
        exit
    fi
    echo "Looking up for : $1"
else
    echo "Unknown Option $1"
    usage
    exit
fi

if [ "$1" == "-g" ];then
    cscope  -d -L -f cscope.out -1 $2
elif [ "$1" == "-s" ];then
    cscope  -d -L -f cscope.out -0 $2
elif [ "$1" == "-c" ];then
    cscope  -d -L -f cscope.out -0 $2
elif [ "$1" == "-e" ];then
    cscope  -d -L -f cscope.out -0 $2
elif [ "$1" == "-f" ];then
    cscope  -d -L -f cscope.out -0 $2
elif [ "$1" == "-vg" ];then
    VCs $1 $2
elif [ "$1" == "-vs" ];then
    VCs $1 $2
elif [ "$1" == "-vc" ];then
    VCs $1 $2
elif [ "$1" == "-ve" ];then
    VCs $1 $2
elif [ "$1" == "-vf" ];then
    VCs $1 $2
fi























#cscoe  -d -L -f cscope.out -0 pufc_regmap
#cscope  -d -L -f cscope.out -7 pufc_unit
#cscope  -d -L -f cscope.out -0 pf_api_dev_access | sort -k 3,3 -g | sort -s -k 1,1
#cscope  -d -l -f cscope.out  0 pf_api_dev_access
#cscope  -d l  0 pf_api_dev_access
#cscope -d cscope.out -R -L0 pf_api_dev_access
#cscope  -L0 pf_api_dev_access
#cscope  cscope.out -R -L0 pf_api_dev_access
