#!/bin/bash
#echo "$1, $2"
if [[ $(cat $1/GFILES |grep -i "$2" | wc -l) -eq 1  ]]; then
	echo "Same file Exists: $2" >> $1/GLOG 
	exit 0
fi
echo "$1|$2" >>$1/GFILES

if [[ -f $1/GRUN ]]; then
	echo "Already Running" >> $1/GLOG
	exit 0
else
	:> $1/GRUN 
fi

#while true
#do
	#line=$(sed '1p' $1/GFILES)
	#$(sed -i '1d' $1/GFILES)
	#echo "CMD = [$line] "
#done


function gtags_update()
{
	(while true
	do
		read a
		if [[ $a == "" ]]; then
			break 
		fi
		dir=$(echo $a | awk -F"|" '{print $1}' )
		cmd=$(echo $a | awk -F"|" '{print $2}' )
		cd "$dir"
		echo "CMD = [$dir, $cmd]" >>$1/GLOG
		`$cmd`

	done)<$1/GFILES

	rm -rf  $1/GRUN 
	:> $1/GFILES
}

function gtags_update_file()
{
	while true
	do
		file="$(sed  '1q;' $1/GFILES ;  sed -i '1d;'  $1/GFILES )";
		
		if [[ $file == "" ]]; then
			break 
		fi
		gfile=$(echo $file | awk -F" " '{print $3}' )
		echo "$gfile" > $1/GFILE 
		dir=$(echo $file | awk -F"|" '{print $1}' )
		cmd=$(echo $file | awk -F"|" '{print $2}' )
		cd "$dir"
		echo "CMD = [$dir, $cmd]" >>$1/GLOG
		`$cmd`
		#sleep 30
		:> $1/GFILE

	done 

	rm -rf  $1/GRUN 
	:> $1/GFILES
}
gtags_update_file $1 &

